wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: huggingface
    huggingface_version: 4.26.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.16
    start_time: 1677924369.552364
    t:
      1:
      - 1
      - 11
      - 40
      - 49
      - 50
      - 51
      - 55
      2:
      - 1
      - 11
      - 40
      - 49
      - 50
      - 51
      - 55
      3:
      - 1
      - 23
      4: 3.8.16
      5: 0.13.10
      6: 4.26.0
      8:
      - 5
