hydra:
  run:
    dir: .
  sweep:
    dir: .
    subdir: .
  job_logging:
    root:
      level: INFO
  job:
    env_set:
      TOKENIZERS_PARALLELISM: "false"


model_name_or_path: cross-encoder/nli-deberta-v3-base
data:
  dataset_name: esnli
  dataset_config_name: null
  splits:
    - validation
    - test
batch_size: 8
device: cuda
output_dir: hidden_states/${simple_basename:${model_name_or_path}}_${data.dataset_name}
