hydra:
  run:
    dir: .
  sweep:
    dir: .
    subdir: .
  job_logging:
    root:
      level: INFO
  job:
    env_set:
      TOKENIZERS_PARALLELISM: "false"

model_name_or_path: cross-encoder/nli-deberta-v3-base
data:
  dataset_name: esnli
  dataset_config_name: null
  splits:
    - train
    - validation
    - test
encoder_states: hidden_states/nli-deberta-v3-base_on_esnli.hdf5
batch_size: 64
device: cuda
learning_rate: 0.0005
lstm_hidden_size: 1536
layer: 1
plot_every: 2
print_every: 2
evaluate_every: 2
multi_run: 1
patience: 7
max_epochs: 100
model_name_short: basic_probe
custom_string: halfrandom2